MERCHANTS_BY_SPENDING_CATEGORY = {
    'tunnelbear': 'web',
    'joe & the juice': 'coffee shop',
    'dropbox': 'web',
    'hanahaus': 'work',
    'webfaction': 'web',
    'democracy now': 'entertainment',
    'jougert bar': 'coffee shop',
    'spotify': 'entertainment',
    'howl.fm': 'entertainment',
    'amazon web services': 'web',
    'caffe central': 'coffee shop',
    'google cloud': 'web',
    'safeway': 'grocery',
    'github': 'web',
    'suruki': 'grocery',
    'kaffeehaus': 'coffee shop',
    'onigilly': 'restaurant',
    'empanadas': 'restaurant',
    'sip': 'grocery',
    'crepe': 'restaurant',
    'peet': 'coffee shop',
    'clipper': 'commuting',
    'intercepted': 'donation',
    'youtube': 'entertainment',
    'givedirectly': 'donation',
    'hummus': 'restaurant',
    'hair': 'haircut',
    'pizzeria': 'restaurant',
    'uber trip': 'commuting',
    'uber': 'commuting',
    'aptos': 'restaurant',
    'hlu*hulu': 'entertainment',
    'farm fresh': 'grocery',
    'walmart': 'shopping',
    'comcast': 'internet',
    'netflix': 'entertainment',
    'alaska': 'travel',
    'grubhub': 'restaurant',
    'caviar': 'restaurant',
    'paris baguette': 'coffee shop',
    'davidstea': 'coffee shop',
    'blue bottle': 'coffee shop',
    'mollie stones': 'grocery',
    'century theatres': 'entertainment',
    'digitalocean': 'web',
    'beverages & more': 'grocery',
    'asian box': 'restaurant',
    'hover': 'web',
    'usps': 'misc',
    'itunes': 'entertainment',
    'mingalaba': 'restaurant',
    'geico': 'car',
    'walgreens': 'grocery',
    'calif dmv': 'car',
    'panda express': 'restaurant',
    'target': 'shopping',
    'ace hardware': 'shopping',
    'five little monkeys': 'shopping',
    'intuit': 'tax',
    'nbcsports': 'entertainment',
    'stamps.com': 'misc',
    'ting': 'phone',
    'the intercept': 'donation',
    'nationwide ins': 'renters insurance',
    'jacobin': 'entertainment',
    'cr digital membership': 'donation',
    'blush': 'coffee shop',
    'actblue': 'donation',
    'julia evans': 'work',
    'pragmatic programmers': 'work',
    'mediterranean kebab': 'restaurant',
    'aws': 'web',
    'ikon roastery': 'coffee shop',
    'amazon digital svcs': 'work',
    'yayoi': 'restaurant',
    'wholefds': 'grocery',
    'lyfe kitchen': 'restaurant',
    'fraiche': 'coffee shop',
    'fandango.com': 'entertainment',
    'cha express': 'coffee shop',
    'capital one member fee': 'misc',
    'dbader.org': 'work',
    'lastpass': 'web',
    'delica': 'restaurant',
    'mavi': 'shopping',
    'kiva': 'donation',
    'nachoria': 'restaurant',
    'karla welch': 'haircut',
    'poke shop': 'restaurant',
    'eb introduction to tl': 'work',
    'health ins': 'healthcare',
    'atm withdrawal': 'cash',
    'withdrawal': 'cash',
    'pgande           web online': 'utilities',
    'american express ach': 'credit card balance',
    'chase credit crd autopay': 'credit card balance',
    'franchise tax bo payments': 'taxes',
    'cafe venetia': 'restaurant',
    'international incoming wire fee': 'misc',
    'quickpay with zelle': 'misc',
    'state farm': 'renters insurance',
    'amzn mktp': 'shopping',
    'general nutrition center': 'shopping',
    'amazon.com': 'shopping',
    'amazon prime': 'shopping',
    'the organic coup': 'restaurant',
    'interviewcake.com': 'work',
    'kickstarter.com': 'donation',
    'rei.com': 'shopping',
    'mlb.com': 'entertainment',
    'chase credit crd autopay': 'remove',
    'payment to chase card ending in': 'remove',
    'online transfer to chk': 'remove',
    'american express ach': 'remove',
    'withdrawal 09/27': 'rent'
}

CHASE_CHECKS = {
    'check 195': 'utilities',
    'check 196': 'rent',
    'check 197': 'healthcare',
    'check 198': 'healthcare',
    'check 199': 'utilities',
    'check 200': 'rent',
    'check 201': 'utilities',
    'check 202': 'rent',
    'check 203': 'utilities',
    'check 204': 'rent',
    'check 205': 'renters insurance',
    'check 206': 'renters insurance',
    'check 207': 'utilities',
    'check 208': 'rent',
    'check 209': 'misc',
    'check 210': 'utilities',
    'check 211': 'rent',
    'check 212': 'utilities',
    'check 213': 'rent',
    'check 214': 'utilities',
    'check 215': 'rent',
    'check 216': 'utilities',
    'check 217': 'rent',
    'check 219': 'utilities',
    'check 220': 'rent',
    'check 221': 'rent',
    'check 222': 'rent',
    'check 223': 'rent',
    'check 224': 'utilities',
    'check 225': 'rent',
    'check 226': 'renters insurance'
}
